import { chromium } from 'playwright';
const BASE = "https://www.crede-ti.info";
const r = await fetch(`${BASE}/api/auth/master-login`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({masterPassword:'LuisAdmin2025#'}) });
const { token, user } = await r.json();
const b = await chromium.launch({ executablePath: '/root/.cache/ms-playwright/chromium-1148/chrome-linux/chrome' });
const ctx = await b.newContext({ viewport: { width: 430, height: 1400 } });
const page = await ctx.newPage();
await page.goto(`${BASE}/admin`, { waitUntil:'domcontentloaded' });
await page.evaluate(([t,u]) => { localStorage.setItem('credeti_token',t); localStorage.setItem('credeti_role','admin'); localStorage.setItem('credeti_user', JSON.stringify(u)); }, [token,user]);
await page.goto(`${BASE}/admin/expediente/15`, { waitUntil:'networkidle' });
await page.waitForTimeout(7000);
const t = await page.evaluate(() => document.body.innerText);
const has = s => t.includes(s);
console.log("Datos bancarios (titulo):", has('DATOS BANCARIOS') || has('Datos bancarios'));
console.log("Banco (Mercado pago):", has('Mercado pago'));
console.log("CLABE (722969020637182208):", has('722969020637182208'));
console.log("Titular:", has('Jose Miguel'));
console.log("Como nos conocio (Recomendacion):", has('Recomendacion') || has('Recomendación'));
await page.screenshot({ path: '/root/vforge/bank.png', fullPage: true });
await b.close();
