import { chromium } from 'playwright';
const BASE = "https://www.crede-ti.info";
const r = await fetch(`${BASE}/api/auth/master-login`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({masterPassword:'LuisAdmin2025#'}) });
const { token, user } = await r.json();
const b = await chromium.launch({ executablePath: '/root/.cache/ms-playwright/chromium-1148/chrome-linux/chrome' });
const ctx = await b.newContext({ viewport: { width: 430, height: 760 } });
const page = await ctx.newPage();
await page.goto(`${BASE}/admin`, { waitUntil:'domcontentloaded' });
await page.evaluate(([t,u]) => { localStorage.setItem('credeti_token',t); localStorage.setItem('credeti_role','admin'); localStorage.setItem('credeti_user', JSON.stringify(u)); }, [token,user]);
await page.goto(`${BASE}/admin/expediente/15`, { waitUntil:'networkidle' });
await page.waitForTimeout(7000);
const headerName = await page.evaluate(() => { const el=[...document.querySelectorAll('div')].find(d=>/fontWeight: 800|font-weight: 800/.test(d.getAttribute('style')||'') && (d.textContent||'').length<60); return el?el.textContent:'?'; });
console.log("Encabezado:", headerName);
await page.screenshot({ path: '/root/vforge/exp2.png' });
await b.close();
