import { chromium } from 'playwright';
const BASE = "https://www.crede-ti.info";
const r = await fetch(`${BASE}/api/auth/master-login`, { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({masterPassword:'LuisAdmin2025#'}) });
const { token, user } = await r.json();
const b = await chromium.launch({ executablePath: '/root/.cache/ms-playwright/chromium-1148/chrome-linux/chrome' });
const ctx = await b.newContext({ viewport: { width: 430, height: 1100 } });
const page = await ctx.newPage();
await page.goto(`${BASE}/admin`, { waitUntil:'domcontentloaded' });
await page.evaluate(([t,u]) => { localStorage.setItem('credeti_token',t); localStorage.setItem('credeti_role','admin'); localStorage.setItem('credeti_user', JSON.stringify(u)); }, [token,user]);
await page.goto(`${BASE}/admin/expediente/15`, { waitUntil:'networkidle' });
await page.waitForTimeout(7000);
const txt = await page.evaluate(() => document.body.innerText);
const has = s => txt.includes(s);
console.log("Nombre:", has('Jose Miguel') || has('Gonz'));
console.log("Ocupacion (Comerciante):", has('Comerciante'));
console.log("Ingreso (10000):", has('10000') || has('10,000'));
console.log("Domicilio (atocpan):", has('atocpan') || has('Oaxtepec'));
console.log("CURP:", has('GORM870710'));
console.log("Referencias (Veronica/Joshua):", has('Veronica') || has('Joshua'));
await page.screenshot({ path: '/root/vforge/exp.png', fullPage: true });
await b.close();
